version: '3.8'

services:
  traefik:
    image: docker.io/library/traefik:v2.5
    command:
      - --providers.docker=true
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:3000
      - --api.insecure=true
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.replacePathHealth.replacepath.path=/health
      - traefik.http.middlewares.rateLimiter.ratelimit.average=100
      - traefik.http.middlewares.rateLimiter.ratelimit.burst=50
    networks:
      - internal

  redis:
    image: docker.io/library/redis:7
    container_name: redis
    networks:
      - internal

  user:
    image: docker.io/notmde/rvc-user:fa149f98d9d02c69794b1fd0cfc5a6cc873999b8
    container_name: user-service
    environment:
      - REDIS_URI=redis://redis:6379
      - USER_SERVICE_PORT=5000
      - TURN_URL=
      - TURN_USERNAME=
      - TURN_CRED=
      - SESSION_KEY=secret
      - PRODUCTION_FLAG=0
    labels:
      - traefik.enable=true
      - traefik.http.services.user-service.loadbalancer.server.port=5000
      - traefik.http.routers.userHomeRouter.rule=Path(`/`)
      - traefik.http.routers.userRegisterRouter.rule=Path(`/register`)
      - traefik.http.routers.userMatchRouter.rule=Path(`/match`)
      - traefik.http.routers.userHealthRouter.rule=PathPrefix(`/user/health`)
      - traefik.http.routers.userHealthRouter.middlewares=replacePathHealth,rateLimiter
    networks:
      - internal

  user-connection:
    image: docker.io/notmde/rvc-userconnection:fa149f98d9d02c69794b1fd0cfc5a6cc873999b8
    container_name: user-connection-service
    environment:
      - REDIS_URI=redis://redis:6379
      - USERCONN_SERVICE_PORT=5001
    labels:
      - traefik.enable=true
      - traefik.http.services.chat-service.loadbalancer.server.port=5001
      - traefik.http.routers.chatWSRouter.rule=PathPrefix(`/connection/`)
      - traefik.http.routers.chatHealthRouter.rule=PathPrefix(`/connection/health`)
      - traefik.http.routers.chatHealthRouter.middlewares=replacePathHealth,rateLimiter
    networks:
      - internal

  forwarder:
    image: docker.io/notmde/rvc-forwarder:fa149f98d9d02c69794b1fd0cfc5a6cc873999b8
    container_name: forwarder-service
    environment:
      - REDIS_URI=redis://redis:6379
      - FORWARDER_SERVICE_PORT=5002
    labels:
      - traefik.enable=true
      - traefik.http.services.forwarder-service.loadbalancer.server.port=5002
      - traefik.http.routers.forwarderHealthRouter.rule=PathPrefix(`/forwarder/health`)
      - traefik.http.routers.forwarderHealthRouter.middlewares=replacePathHealth,rateLimiter
    networks:
      - internal

  user-event:
    image: docker.io/notmde/rvc-userevent:fa149f98d9d02c69794b1fd0cfc5a6cc873999b8
    container_name: user-event-service
    environment:
      - REDIS_URI=redis://redis:6379
      - USEREVENT_SERVICE_PORT=5003
    labels:
      - traefik.enable=true
      - traefik.http.services.user-event-service.loadbalancer.server.port=5003
      - traefik.http.routers.usereventHealthRouter.rule=PathPrefix(`/userevent/health`)
      - traefik.http.routers.usereventHealthRouter.middlewares=replacePathHealth,rateLimiter
    networks:
      - internal

networks:
  internal:
    driver: bridge