version: '3.8'

services:
  traefik:
    image: docker.io/library/traefik:v2.5
    command:
      - --providers.docker=true
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:3000
      - --api.insecure=true
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.rateLimiter.ratelimit.average=100
      - traefik.http.middlewares.rateLimiter.ratelimit.burst=50
    networks:
      - internal

  redis:
    image: docker.io/library/redis:7
    container_name: redis
    networks:
      - internal

  user:
    image: docker.io/notmde/rvc-user:fa149f98d9d02c69794b1fd0cfc5a6cc873999b8
    container_name: user-service
    depends_on:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379
      - USER_SERVICE_PORT=5000
      - TURN_URL=
      - TURN_USERNAME=
      - TURN_CRED=
      - SESSION_KEY=secret
      - PRODUCTION_FLAG=0
    labels:
      - traefik.enable=true
      - traefik.http.services.user-service.loadbalancer.server.port=5000
      - traefik.http.routers.userHomeRouter.rule=Path(`/`)
      - traefik.http.routers.userHomeRouter.middlewares=rateLimiter
      - traefik.http.routers.userRegisterRouter.rule=Path(`/register`)
      - traefik.http.routers.userRegisterRouter.middlewares=rateLimiter
      - traefik.http.routers.userMatchRouter.rule=Path(`/match`)
      - traefik.http.routers.userMatchRouter.middlewares=rateLimiter
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "-S", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - internal

  user-connection:
    image: docker.io/notmde/rvc-userconnection:fa149f98d9d02c69794b1fd0cfc5a6cc873999b8
    container_name: user-connection-service
    depends_on:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379
      - USERCONN_SERVICE_PORT=5001
    labels:
      - traefik.enable=true
      - traefik.http.services.user-connection-service.loadbalancer.server.port=5001
      - traefik.http.routers.userconnWSRouter.rule=PathPrefix(`/connection/`)
      - traefik.http.routers.userconnWSRouter.middlewares=rateLimiter
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "-S", "http://localhost:5001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - internal

  forwarder:
    image: docker.io/notmde/rvc-forwarder:fa149f98d9d02c69794b1fd0cfc5a6cc873999b8
    container_name: forwarder-service
    depends_on:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379
      - FORWARDER_SERVICE_PORT=5002
    labels:
      - traefik.enable=false
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "-S", "http://localhost:5002/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - internal

  user-event:
    image: docker.io/notmde/rvc-userevent:fa149f98d9d02c69794b1fd0cfc5a6cc873999b8
    container_name: user-event-service
    depends_on:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379
      - USEREVENT_SERVICE_PORT=5003
    labels:
      - traefik.enable=false
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "-S", "http://localhost:5003/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - internal

networks:
  internal:
    driver: bridge