name: CI User Event

on:
  push:
    branches:
      - main
    paths:
      - 'cmd/userevent_service/**'
      - 'internal/common/**'
      - 'internal/models/**'
      - 'internal/services/userevent/**'
      - 'Dockerfile.userevent'
      - '!docker-compose.yml'
      - '!assets/**'
      - '!config/**'
      - '!web/**'
      - '!README.md'

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.userevent
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rvc-userevent:${{ github.sha }}